server:
  port: 8082
spring:
  application:
    name: lagou-server-resume
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&&serverTimezone=UTC
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      naming:
        #避免驼峰命名转换成下划线命名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    nacos:
      discovery:
        # 集群中各节点信息都配置在这⾥（域名-VIP-绑定映射到各个实例的地址信息）
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: 83faa9bf-9b3b-4dc5-a3b5-77e61b2692a8
        group: DEFAULT_GROUP