server:
  port: 8080
spring:
  application:
    name: lagou-server-resume
  #zipkin client 配置
  zipkin:
    # zipkin server的请求地址
    base-url: http://127.0.0.1:9411
    # web 客户端将踪迹⽇志数据通过⽹络请求的⽅式传送到服务端，另外还有配置
    # kafka/rabbit 客户端将踪迹⽇志数据传递到mq进⾏中转
    sender:
      type: web
  sleuth:
    sampler:
      # 采样率 1 代表100%全部采集 ，默认0.1 代表10% 的请求踪迹数据会被采集
      # ⽣产环境下，请求量⾮常⼤，没有必要所有请求的踪迹数据都采集分析，对于⽹络包括
      #server端压⼒都是⽐较⼤的，可以配置采样率采集⼀定⽐例的请求的踪迹数据进⾏分析即可
      probability: 1

eureka:
  instance:
    prefer-ip-address: true #实例显示名称 (早期版本默认显示的是主机名  - LAPTOP-LLGBERGE.lan:lagou-server-resume:8080 )
      #新版本默认是 ip  为了兼容老版本 注意 不自定义instance-id的话  实例显示没有变化
      #自定义eureka实例显示名称   192.168.199.210:lagou-server-resume:8080
      #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    #自定义元数据
    metadata-map:
      cluster: cl1
      rigin: ri1
  client:
    service-url: #连接 eureka server 的路径  #把 eureka 集群中的所有 url 都填写了进来，也可以只写⼀台，因为各个 eureka server 可以同步注册表
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
    fetch-registry: true
    register-with-eureka: true
#分布式链路追踪
logging:
  level:
   org.springframework.web.servlet.DispatcherServlet: debug
   org.springframework.cloud.sleuth: debug