server:
  port: 9003
#注册到Eureka服务中⼼
eureka:
  client:
   service-url:
  # 注册到集群，就把多个Eurekaserver地址使⽤逗号连接起来即可；注册到单实例（⾮集群模式），那就写⼀个就ok
    defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
  #测试访问：http://localhost:9006/master/lagou-service-resume-dev.yml，查看到配置⽂件内容
   #4）构建Client客户端（在已有简历微服务基础上）已有⼯程中添加依赖坐标
   #application.yml修改为bootstrap.yml配置⽂件
   prefer-ip-address: true #服务实例中显示ip，⽽不是显示主机名（兼容⽼的eureka版本）
   # 实例名称： 192.168.1.103:lagou-service-resume:8080，我们可以⾃定义它
   instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
   name: lagou-cloud-config-server-9003

#针对的被调⽤⽅微服务名称,不加就是全局⽣效
#lagou-server-resume:
# ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整

# springboot中暴露健康检查等断点接⼝
management:
  endpoints:
   web:
    exposure:
     include: "*"
  # 暴露健康接⼝的细节
  endpoint:
   health:
    show-details: always