server:
  port: 8080
spring:
  application:
    name: lagou-server-resume
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&&serverTimezone=UTC
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      naming:
        #避免驼峰命名转换成下划线命名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    service-url: #连接 eureka server 的路径  #把 eureka 集群中的所有 url 都填写了进来，也可以只写⼀台，因为各个 eureka server 可以同步注册表
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
    fetch-registry: true
    register-with-eureka: true