server:
  port: 8092
spring:
  application:
    name: lagou-cloud-autodeliver-feign-8092
  #配置消息队列信息
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    #username: guest
    #password: guest
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: #把 eureka 集群中的所有 url 都填写了进来，也可以只写⼀台，因为各个 eurekaserver 可以同步注册表
      defaultZone: http://lagoucloudeurekaservera:8761/eureka/,http://lagoucloudeurekaserverb:8762/eureka/
  instance:
    #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@

#针对的被调⽤⽅微服务名称,不加就是全局⽣效
lagou-service-resume:
   ribbon:
    #请求连接超时时间
    #ConnectTimeout: 2000
    #请求处理超时时间
    ReadTimeout: 5000
    #对所有操作都进⾏重试
    OkToRetryOnAllOperations: true
    ####根据如上配置，当访问到故障请求的时候，它会再尝试访问⼀次当前实例（次数由MaxAutoRetries配置），
    ####如果不⾏，就换⼀个实例进⾏访问，如果还不⾏，再换⼀次实例访问（更换次数由MaxAutoRetriesNextServer配置），
    ####如果依然不⾏，返回失败信息。
    MaxAutoRetries: 0 #对当前选中实例重试次数，不包括第⼀次调⽤
    MaxAutoRetriesNextServer: 0 #切换实例的重试次数
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整
# 开启Feign的熔断功能
feign:
  hystrix:
   enabled: true
  #Feign ⽀持对请求和响应进⾏GZIP压缩，以减少通信过程中的性能损耗。通过下⾯的参数 即可开启请求#与响应的压缩功能
  compression:
    request:
     enabled: true # 开启请求压缩
     mime-types: text/html,application/xml,application/json # 设置压缩的数据类型，此处也是默认值
     min-request-size: 2048 # 设置触发压缩的⼤⼩下限，此处也是默认值 压缩是个算法  不设置条件浪费cpu资源
    response:
     enabled: true # 开启响应压缩
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
# feign 默认超时时间为一秒   如果ribbon设置超时间  ReadTimeout(请求处理时间) 那么就用ribbon的超时时间
#另外一个就是hystrix 的超时时间  超过超时时间熔断调用failback的方法直接返回结果   如果ribbon 还没有做完重试 切换实例的那么会继续执行
#实际过程中 hystrix的超时时间要等于于ribbon 请求处理 重试 切换的时间总和 之后
#重点 如果 ribbon的超时时间小于hystrix的超时时间 并且 没有重试和切换实例那么 那么ribbon超时后 hystrix调用failback方法


#feign日志 依赖于logger的debug级别
logging:
  level:
  # Feign⽇志只会对⽇志级别为debug的做出响应
   com.lagou.edu.service.ResumeFeignClient: debug